### ISSUE TITLE
can't run in sensu

### ISSUE THREAD

**Issue by Negashev** [m4ce/sensu-plugins-rancher-service#1]
I run in rancher, container with 

`https://github.com/sstarcher/docker-sensu`

and install m4ce/rancher-service

afte run get error with `block in <class:CLI>` in sensu

root@9e9aea7e41d2:/# check-rancher-service.rb 

Check failed to run: undefined method `each' for nil:NilClass, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rancher-service-0.0.20/bin/check-rancher-service.rb:106:in`block in run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rancher-service-0.0.20/bin/check-rancher-service.rb:96:in `each'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-rancher-service-0.0.20/bin/check-rancher-service.rb:96:in`run'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in class:CLI'"]

**Comment by Negashev** [comment]
[service['containers']](https://github.com/m4ce/sensu-plugins-rancher-service/blob/master/bin/check-rancher-service.rb#L106) can be empty

**Comment by m4ce** [comment]
Hi,

so, you have a service set up with no instances?

M

**Comment by Negashev** [comment]
it's really strange, but I've used from the catalog kibana4
![screenshot 1](https://cloud.githubusercontent.com/assets/4653589/15530510/41fea52e-226e-11e6-8fa1-7dcd3295bea5.png)

**Comment by m4ce** [comment]
it could be that it fails over another service. Do you have any services (in any stack) that has no instances set up?
